# Generated by Django 3.1.5 on 2022-01-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('logo_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('features_description', models.TextField()),
                ('color', models.CharField(choices=[('white', 'white'), ('red', 'red'), ('green', 'green'), ('grey', 'grey'), ('grey', 'grey'), ('blue', 'blue'), ('orange', 'orange'), ('orange', 'orange'), ('black', 'black')], max_length=256)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='cars.manufacturer')),
            ],
        ),
    ]
