# Generated by Django 3.1.5 on 2022-01-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_manufacturerbasecountry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturerbasecountry',
            options={'verbose_name': 'Manufacturer Country', 'verbose_name_plural': 'Manufacturer Country'},
        ),
        migrations.AlterField(
            model_name='manufacturerbasecountry',
            name='name',
            field=models.CharField(choices=[('None', 'none'), ('German', 'german'), ('Japanese', 'japanese'), ('American', 'american')], max_length=30, unique=True),
        ),
    ]
