# Generated by Django 3.1.5 on 2022-01-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220114_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='base_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_country', to='cars.manufacturerbasecountry'),
            preserve_default=False,
        ),
    ]
